
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtqpgewedhbprmebghhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0cXBnZXdlZGhicHJtZWJnaGhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4ODc3ODIsImV4cCI6MjA1ODQ2Mzc4Mn0.VXGqqNep5bU5BDuQE1NCrm2xQYz0I1uBiEipUBY0ODg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
